name: prod

on:
  push:
    branches: ["master"]
  workflow_dispatch:

permissions:
  contents: read
  packages: write

concurrency:
  group: prod-${{ github.ref }}
  cancel-in-progress: false

jobs:
  deploy:
    environment: production
    runs-on: [self-hosted, k3s, deployer, kasperrt-ShotTimer]
    steps:
      - uses: actions/checkout@v5
      - run: .build/scripts/build-image.sh
        env:
          VITE_HOST: https://etys.no
          VITE_CORS: https://etys.no,https://www.etys.no
      - run: .build/scripts/push-image.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: .build/scripts/deploy.sh
        env:
          NAMESPACE: shottimer
          DEPLOYMENT: shottimer
